jquery_lang_js.prototype.lang.en = {
	'<div class="icon"></div>Profilim': '<div class="icon"></div>Profile',
	'<div class="icon"></div>Hesap Ayarları': '<div class="icon"></div>Account Settings',
	'<div class="icon"></div>Çıkış Yap': '<div class="icon"></div>Log out',
	'<a onclick="window.lang.change(\'en\');">english</a>': '<a onclick="window.lang.change(\'tr\');">türkçe</a>',
	'anasayfa': 'homepage',
	'duvar yarat!': 'build wall!',
	'hakkında': 'about',
	'gizlilik ve kullanım': 'privacy and usage',
	'güncellemeler': 'blog',
	'iletişim': 'contact',
	'sss': 'faq',
	'nedir?': '<p style="margin-left: -3px; ">what\'s?</p>',
	'keşfet!': '<p style="margin-left: -6px; ">discover!</p>',
	'platformlar.': '<p style="margin-left: 4px; ">platforms.</p>',
	'hemen başla!': 'build a wall!',
	'giriş yap / kaydol': 'login / sign up',
	'duvarını yarat!': 'create your wall!',
	'bwallo. / duvarını yarat!': 'bwallo. / create your wall!',
	'bwallo. / Giriş Yap': 'bwallo. / Log In',
	'bwallo. / Kayıt Ol': 'bwallo. / Sign Up',
	'bwallo. / Hakkında': 'bwallo. / About',
	'bwallo. / Gizlilik ve Kullanım': 'bwallo. / Privacy and Usage',
	'bwallo. / Platformlar': 'bwallo. / Platforms',
	'bwallo. / Sıkça Sorulan Sorular': 'bwallo. / Frequently Asked Questions',
	'Hoşgeldin, Giriş Yap': 'Welcome, Log In',
	'e-posta adresi': 'e-mail address',
	'şifre': 'password',
	'Giriş Yap': 'Sign In',
	'Kayıt Ol': 'Sign Up',
	'<span>facebook</span>\'la giriş yap!': 'connect with <span>facebook</span>!',
	'<span>twitter</span>\'la giriş yap!': 'sign in with <span>twitter</span>!',
	'<span>google</span>\'la giriş yap!': 'sign in with <span>google</span>!',
	'beni hatırla!': 'remember!',
	'şifremi unuttum.': 'forgot password.',
	'Hemen Kayıt Ol!': 'Register Now!',
	'<span>facebook</span>\'la kayıt ol!': 'sign up with <span>facebook</span>!',
	'<span>twitter</span>\'la kayıt ol!': 'sign up with <span>twitter</span>!',
	'<span>google</span>\'la kayıt ol!': 'sign up with <span>google</span>!',
	'ad ve soyad': 'full name',
	'kullanıcı adı': 'username',
	'Kayıt Ol': 'Sign Up',
	'* butona tıklayarak <a href="#">koşulları</a> kabul etmiş olursun.': '* by clicking this button, you agree to our <a href="#">terms</a>.',
	'Bir şeyler ara...': 'Search for something...',
	'Takip et!': 'Follow!',
	'Takibi bırak!': 'Unfollow!',
	'Takip ediyorsun': 'Following',
	'Profili Düzenle': 'Edit Profile',
	'Senin duvarların': 'Your walls',
	'Hesap Ayarları': 'Account Settings',
	'Hesap bilgileri': 'Account',
	'Hesap Bilgileri': 'Account',
	'Şifre': 'Password',
	'E-posta bildirimleri': 'E-mail notifications',
	'Profil': 'Profile',
	'Sosyal ağlar': 'Social networks',
	'Eklentiler': 'Goodies',
	'Temel hesap bilgilerini güncelle, hesap ayarlarını değiştir.': 'Change your basic account settings and update your account.',
	'bwallo<span>.</span> hakkında': 'about the bwallo<span>.</span>',
	'iletişim<span>.</span>': 'contact<span>.</span>',
	'gizlilik ve kullanım koşulları<span>.</span>': 'privacy & usage conditions<span>.</span>',
	'sıkça sorulan sorular<span>.</span>': 'frequently asked questions<span>.</span>',
	'platformlar<span>.</span>': 'platforms<span>.</span>',
	'Hakkında': 'About',
	'Parolayı Yeniden Gönder': 'Resend Password',
	'Gizlilik ve Kullanım Koşulları': 'Privacy and Usage Conditions',
	'Platformlar': 'Platforms',
	'Sıkça Sorulan Sorular': 'Frequently Asked Questions',
	'İletişim': 'Contact',
	'Sakin ol! Sadece istediğin sayfayı bulamadık.': 'Stay calm! We just can\'t find the page you were looking for.',
	'Anasayfaya geri dön': 'Back to homepage'
}